language: scala

env:
  matrix:
    - HAXE_FILE=haxe_latest.tar.gz
    - HAXE_FILE=haxe_2014-09-19_development_9f5b3f5.tar.gz
    - HAXE_FILE=haxe_2014-10-21_development_a05b532.tar.gz


before_install:
 - travis_retry sudo add-apt-repository ppa:eyecreate/haxe -y
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq neko ocaml mono-devel 
 - travis_retry wget http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/"$HAXE_FILE"
 - sudo tar zxvf "$HAXE_FILE"
 - sudo mv haxe-* haxe
 - export PATH=$PATH:`pwd`/haxe
 - export HAXE_STD_PATH=`pwd`/haxe/std
 - travis_retry haxelib setup .haxelib
 - travis_retry haxelib install nodejs
 - travis_retry haxelib install hxjava
 - travis_retry haxelib install hxcs
