language: scala

before_install:
 - travis_retry sudo add-apt-repository ppa:eyecreate/haxe -y
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq neko ocaml mono-devel 
 - travis_retry wget http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/haxe_latest.tar.gz
 - sudo tar zxvf haxe_latest.tar.gz
 - sudo mv haxe-* haxe
 - export PATH=$PATH:`pwd`/haxe
 - which haxe
 - which haxelib
 - travis_retry sudo haxelib setup .haxelib
 - travis_retry sudo haxelib install nodejs
 - travis_retry sudo haxelib install hxjava
 - travis_retry sudo haxelib install hxcs
